<?php
namespace Magestore\Auction\Model\Source;

class Biddernametype{
    const GENNERATE_BY_SYSTEM = 1;
    const CREATE_BY_CUSTOMER = 2;
    const BASE_ON_CUSTOMERS_NAME = 3;
    public function toOptionArray()
    {
        return array(
            array('value'=>self::GENNERATE_BY_SYSTEM, 'label'=>__('Generated by System')),
            array('value'=>self::CREATE_BY_CUSTOMER, 'label'=>__('Created by Customers')),
            array('value'=>self::BASE_ON_CUSTOMERS_NAME, 'label'=>_('Based on Customer\'s Name')),
        );
    }
}