<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\Backend\Block\Widget\Grid\Serializer
 */
?>
<?php $_id = 'id_' . md5(microtime()) ?>
<?php $formId = $block->getFormId()?>
<?php if (!empty($formId)) :?>
    <script>
        require([
            'prototype',
            'mage/adminhtml/grid'
        ], function(){
            Event.observe(window, "load", function(){
                var serializeInput  = document.createElement('input');
                serializeInput.type = 'hidden';
                serializeInput.name = '<?php /* @escapeNotVerified */ echo $block->getInputElementName()?>';
                serializeInput.id   = '<?php /* @escapeNotVerified */ echo $_id?>';
                try {
                    document.getElementById('<?php /* @escapeNotVerified */ echo $formId?>').appendChild(serializeInput);
                    new serializerController('<?php /* @escapeNotVerified */ echo $_id?>', <?php /* @escapeNotVerified */ echo $block->getDataAsJSON() ?>, <?php /* @escapeNotVerified */ echo $block->getColumnInputNames(true) ?>, <?php /* @escapeNotVerified */ echo $block->getGridBlock()->getJsObjectName() ?>, '<?php /* @escapeNotVerified */ echo $block->getReloadParamName()?>');
                    <?php /* @escapeNotVerified */ echo $block->getGridBlock()->getJsObjectName() ?>.rowClickCallback = function(){};
                } catch(e) {
                    //Error add serializer
                }
            });
        });
    </script>
<?php else :?>
    <input type="hidden" name="<?php /* @escapeNotVerified */ echo $block->getInputElementName()?>"  value="" id="<?php /* @escapeNotVerified */ echo $_id?>" />
    <script>
        require([
            'mage/adminhtml/grid'
        ], function(){
            new serializerController('<?php /* @escapeNotVerified */ echo $_id?>', <?php /* @escapeNotVerified */ echo $block->getDataAsJSON() ?>, <?php /* @escapeNotVerified */ echo $block->getColumnInputNames(true) ?>, <?php /* @escapeNotVerified */ echo $block->getGridBlock()->getJsObjectName() ?>, '<?php /* @escapeNotVerified */ echo $block->getReloadParamName()?>');
            <?php /* @escapeNotVerified */ echo $block->getGridBlock()->getJsObjectName() ?>.rowClickCallback = magestoreObjectRowClick;
        });
    </script>
<?php endif;?>
<script>
    function magestoreObjectRowClick(grid, event){
        var trElement = Event.findElement(event, 'tr');
        if(trElement){
            var checkbox = Element.getElementsBySelector(trElement, 'input');
            if(checkbox[0]){
                jQuery('#<?php echo $_id ?>').value = checkbox[0].value;
                checkbox[0].checked = true;
                jQuery.ajax( {
                    url: "<?php echo $this->getChangeProductUrl() ?>",
                    data: {product_id: checkbox[0].value},
                    showLoader: true,
                    type: 'POST'
                }).done(function(a) {
                    jQuery('#auction_tabs_main_section').get(0).click();
                    jQuery('#page_name').get(0).value = a.name;
                    jQuery('input[name=product_id]').get(0).value = a.id;
                    jQuery('#product_edit_link').get(0).href = a.url;
                });
            }
        }
    }
</script>
