<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Catalog\Product\View\Addto\Compare */
?>
<?php /* ?>
<a href="#" data-post='<=$block->getPostDataParams();?>'
        data-role="add-to-links"
        class="action tocompare"><span><?=__('Add to Compare') ?></span></a>
<?php */ ?>