
<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * Bids view template
 *
 * @var $this \Magestore\Auction\Block\Myautobid
 * @var $_bid \Magestore\Auction\Model\Autobid
 * @var $_bidder \Magestore\Auction\Model\Bidder
 */
?>
<?php $_bidder = $this->getCurrentBidder(); ?>
<?php if($_bidder->isEnabled()): ?>
    <?php $_bids   = $this->getBids(); ?>
    <?php if ($_bids->getSize()): ?>
        <div class="table-wrapper bids-history">
            <table class="data table table-bid-items history" id="my-bids-table">
                <caption class="table-caption"><?php  echo __('My Bid') ?></caption>
                <thead>
                <tr>
                    <th scope="col" class="col product_name"><?php  echo __('PRODUCT NAME') ?></th>
                    <th scope="col" class="col bid_price"><?php  echo __('BID PRICE') ?></th>
                    <th scope="col" class="col created_time"><?php  echo __('CREATED TIME') ?></th>
                    <th scope="col" class="col status"><?php  echo __('STATUS') ?></th>
                    <?php if($this->isCancelAble()): ?>
                        <th scope="col" class="col action"><?php  echo __('ACTION') ?></th>
                    <?php endif; ?>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($_bids as $_bid): ?>
                    <tr>
                        <td data-th="<?php echo $this->escapeHtml(__('Product Name')) ?>" class="col product_name"><?php  echo $_bid->getAuctionName() ?></td>
                        <td data-th="<?php echo $this->escapeHtml(__('Bid Price')) ?>" class="col bid_price"><?php  echo $_bid->getPriceText() ?></td>
                        <td data-th="<?php echo $this->escapeHtml(__('Created Time')) ?>" class="col created_time"><?php echo $_bid->getFormatedTime() ?></td>
                        <td data-th="<?php echo $this->escapeHtml(__('Status')) ?>" class="col status"><?php  echo $_bid->getStatusLabel() ?></td>
                        <?php if($this->isCancelAble()): ?>
                            <td data-th="<?php echo $this->escapeHtml(__('Action')) ?>" class="col action"><a href="<?php  echo $this->getCancelBid($_bid->getId()) ?>" ><?php echo __('Cancel') ?></a></td>
                        <?php endif; ?>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <?php if ($this->getPagerHtml()): ?>
            <div class="order-products-toolbar toolbar bottom"><?php echo $this->getPagerHtml(); ?></div>
        <?php endif ?>
    <?php else: ?>
        <div class="message info empty"><span><?php  echo __('You have placed no autobids.'); ?></span></div>
    <?php endif ?>
<?php endif ?>