<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = __('New Products');
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
}

$_helper = $this->helper('Magestore\Auction\Helper\Auction');
?>
<?php if ($exist):?>
    <div class="block fadeInUp widget block-products-list <?php /* @escapeNotVerified */ echo $mode; ?>">
        <div class="block-title">
            <strong role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
        </div>
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <ol class="product-items slick <?php /* @escapeNotVerified */ echo $type; ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                            </a>
                            <div class="product-item-details">
                                <div class="justify main-info-detail">
                                    <strong class="product-item-name">
                                        <?php echo "<span>".$_item->getSpecialPrice()."</span>"; ?>
                                        <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                           href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                           class="product-item-link">
                                            <?php echo $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>
                                    <?php echo $block->getProductPriceHtml($_item, $type); ?>
                                </div>
                                <?php if ($templateType): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>
                                <?php $auction = $_helper->getAuctionByProductId($_item->getId()); ?>
                                <!-- ToDo: must be programmed -->
                                <div class="justify additional-info-detail">
                                    <div class="additional-details">
                                        <span class="distance">123 000 км</span>
                                        <span class="engine_type">Дизель</span>
                                        <span class="doors_quantity">4 двери</span>
                                        <span class="engine_value">1.6 л</span>
                                        <span class="box">Автомат</span>
                                        <span class="city">Киев</span>
                                    </div>
                                    <?php if(!empty($auction)) : ?>
                                    <div class="<?=$type?>_slider_countdown_<?=$auction['product_id']?> <?=$auction['countdown']['class']?> slider_countdown_list"
                                         product-id="<?=$auction['product_id']?>"
                                         data-seconds-left="<?=$auction['countdown']['time']?>"></div>
                                    <script>
                                        require(['jquery','magestore/countdown'], function($){
                                            $('.<?=$type?>_slider_countdown_<?=$auction['product_id']?>').startTimer({timeText:'<?=$auction['countdown']['type']; ?> <?php echo __('<span class="height-timebox"><span id="daytime">%d&nbsp;</span><span id="hourtime">%h</span><span id="tspace">:</span><span id="mtime">%m</span><span id="tspace">:</span><span id="sctime">%s</span></span>') ?>'});
                                        });
                                    </script>
                                    <?php endif; ?>
                                </div>
                                <!--buttons block are removed from here-->
                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>

    </div>
<?php endif;?>
